name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v8
    - uses: actions/setup-python@v2 # For misc/embedded_nnue_data.py
    - run: npm run prepare
